import { Cast } from '../types/social';
import { mockUsers } from './users';

export const mockCasts: Cast[] = [
  {
    id: '1',
    author: mockUsers[0],
    content: 'The future of social networks is decentralized. No single entity should control our digital identities and connections.',
    timestamp: '2024-01-20T10:30:00Z',
    likesCount: 1234,
    recastsCount: 456,
    repliesCount: 89,
    isLiked: false,
    isRecasted: false,
  },
  {
    id: '2',
    author: mockUsers[1],
    content: 'Just shipped a major update to the protocol. Excited to see what builders create with these new primitives! 🚀',
    timestamp: '2024-01-20T09:15:00Z',
    likesCount: 892,
    recastsCount: 234,
    repliesCount: 67,
    isLiked: true,
    isRecasted: false,
  },
  {
    id: '3',
    author: mockUsers[2],
    content: 'Onchain is the next online. Every interaction, every relationship, every transaction - all verifiable and composable.',
    images: ['https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=400&fit=crop'],
    timestamp: '2024-01-20T08:45:00Z',
    likesCount: 2341,
    recastsCount: 678,
    repliesCount: 123,
    isLiked: false,
    isRecasted: true,
  },
  {
    id: '4',
    author: mockUsers[3],
    content: 'The network state is not just a concept - it\'s becoming reality. Digital communities with real economic and political power.',
    timestamp: '2024-01-19T22:30:00Z',
    likesCount: 3456,
    recastsCount: 1234,
    repliesCount: 234,
    isLiked: true,
    isRecasted: false,
  },
  {
    id: '5',
    author: mockUsers[4],
    content: 'Interesting to see how NFT communities are evolving into full-fledged DAOs with governance and treasury management.',
    timestamp: '2024-01-19T20:15:00Z',
    likesCount: 567,
    recastsCount: 123,
    repliesCount: 45,
    isLiked: false,
    isRecasted: false,
  },
  {
    id: '6',
    author: mockUsers[5],
    content: 'The open metaverse is not about VR headsets. It\'s about open protocols, interoperable assets, and user ownership.',
    images: ['https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=400&fit=crop'],
    timestamp: '2024-01-19T18:00:00Z',
    likesCount: 1890,
    recastsCount: 456,
    repliesCount: 89,
    isLiked: true,
    isRecasted: true,
  },
  {
    id: '7',
    author: mockUsers[6],
    content: 'Just deployed my first smart contract on Stacks! The developer experience is amazing. @dwr would love your thoughts on this.',
    mentions: ['dwr'],
    timestamp: '2024-01-19T16:30:00Z',
    likesCount: 234,
    recastsCount: 45,
    repliesCount: 23,
    isLiked: false,
    isRecasted: false,
  },
  {
    id: '8',
    author: mockUsers[7],
    content: 'DeFi summer was just the beginning. We\'re entering the era of decentralized everything - social, identity, storage, compute.',
    timestamp: '2024-01-19T14:45:00Z',
    likesCount: 678,
    recastsCount: 156,
    repliesCount: 34,
    isLiked: false,
    isRecasted: false,
  },
  {
    id: '9',
    author: mockUsers[0],
    content: 'Proof of stake is not just about energy efficiency. It\'s about enabling new forms of coordination and governance.',
    timestamp: '2024-01-19T12:00:00Z',
    likesCount: 2890,
    recastsCount: 890,
    repliesCount: 167,
    isLiked: true,
    isRecasted: false,
  },
  {
    id: '10',
    author: mockUsers[1],
    content: 'The best way to predict the future is to build it. That\'s what we\'re doing with decentralized social.',
    images: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop'],
    timestamp: '2024-01-19T10:30:00Z',
    likesCount: 1456,
    recastsCount: 345,
    repliesCount: 78,
    isLiked: false,
    isRecasted: false,
  },
  {
    id: '11',
    author: mockUsers[2],
    content: 'Base is growing faster than we imagined. Millions of transactions, thousands of developers, and we\'re just getting started.',
    timestamp: '2024-01-18T22:15:00Z',
    likesCount: 3234,
    recastsCount: 1123,
    repliesCount: 234,
    isLiked: true,
    isRecasted: true,
  },
  {
    id: '12',
    author: mockUsers[4],
    content: 'The intersection of AI and crypto is going to be wild. Autonomous agents with wallets, trading on-chain, coordinating in DAOs.',
    timestamp: '2024-01-18T20:00:00Z',
    likesCount: 1890,
    recastsCount: 567,
    repliesCount: 123,
    isLiked: false,
    isRecasted: false,
  },
];
