import { Channel } from '../types/social';

export const mockChannels: Channel[] = [
  {
    id: '1',
    name: 'crypto',
    description: 'All things cryptocurrency and blockchain',
    image: '💰',
    membersCount: 45000,
    castsCount: 123456,
    createdBy: '1',
    createdAt: '2023-01-15',
  },
  {
    id: '2',
    name: 'defi',
    description: 'Decentralized finance discussions',
    image: '🏦',
    membersCount: 32000,
    castsCount: 89234,
    createdBy: '2',
    createdAt: '2023-01-20',
  },
  {
    id: '3',
    name: 'nfts',
    description: 'NFT art, collections, and culture',
    image: '🎨',
    membersCount: 28000,
    castsCount: 67890,
    createdBy: '5',
    createdAt: '2023-02-01',
  },
  {
    id: '4',
    name: 'builders',
    description: 'For developers building on web3',
    image: '🛠️',
    membersCount: 19000,
    castsCount: 45678,
    createdBy: '6',
    createdAt: '2023-02-10',
  },
  {
    id: '5',
    name: 'daos',
    description: 'DAO governance and coordination',
    image: '🏛️',
    membersCount: 15000,
    castsCount: 34567,
    createdBy: '3',
    createdAt: '2023-02-15',
  },
  {
    id: '6',
    name: 'memes',
    description: 'Crypto memes and shitposting',
    image: '😂',
    membersCount: 56000,
    castsCount: 234567,
    createdBy: '7',
    createdAt: '2023-01-25',
  },
  {
    id: '7',
    name: 'stacks',
    description: 'Stacks blockchain community',
    image: '📚',
    membersCount: 12000,
    castsCount: 23456,
    createdBy: '1',
    createdAt: '2023-03-01',
  },
  {
    id: '8',
    name: 'ethereum',
    description: 'Ethereum ecosystem and development',
    image: '⟠',
    membersCount: 67000,
    castsCount: 345678,
    createdBy: '0',
    createdAt: '2023-01-10',
  },
];
